---
title: "00-test"
output: html_notebook
---

## Load packages
```{r}
library(tidyverse)
library(janitor)
library(assertr)
library(stringr)
library(lubridate)
library(zipcode)
library(gganimate)
library(ggpubr)
library(gridExtra)
library(ggalluvial)
library(purrrlyr)
library(sf)
```


```{r}
# Please unrara the "transformed.rar" file manually first.
original_file <- read_csv("data/transformed.csv") %>% 
  clean_names()
#file.remove("data/transformed.csv")
stem <- read_csv("data/stem_list.csv")
```
#Removing Coli Extraneous  Columns

```{r}
DATA <- original_file %>% 
  select(- c('coli_x', 'coli_y')) %>% 
  mutate(case_status=str_to_lower(case_status)) %>% 
  mutate(employer_name=str_to_lower(employer_name)) %>%  
  mutate(soc_name=str_to_lower(soc_name)) %>%  
  mutate(job_title=str_to_lower(job_title)) %>% 
  mutate(full_time_position = case_when(full_time_position=="Y"~1,
                                        full_time_position=="N"~0)) %>% 
  mutate(full_time_position=factor(full_time_position)) %>% 
  mutate(worksite_city=str_to_lower(worksite_city)) %>% 
  mutate(worksite_state_abb=str_to_upper(worksite_state_abb)) %>% 
  mutate(worksite_state_full=str_to_lower(worksite_state_full)) %>% 
  mutate(worksite=str_to_lower(worksite)) 

head(DATA)
```


# Adding the new feature called `soc_field` to represent the higher level of job fields.
```{r}
DATA <- DATA %>% 
  filter(str_detect(soc_code, "^\\d{2}(-)\\d{4}$")) %>% 
  mutate(soc_field = substr(soc_code, start = 1, stop = 2)) %>% 
  filter(as.numeric(soc_field) %% 2 != 0) %>% 
  filter(soc_field != 71) %>% 
  select(soc_field, soc_code, job_title, everything())
```


# Conform the top tech companies's name
```{r}
DATA <- DATA %>% 
  mutate(employer_name = ifelse(str_detect(employer_name,'apple inc'), 'apple',
                          ifelse(str_detect(employer_name,'microsoft'), 'microsoft',
                          ifelse(str_detect(employer_name,'amazon'),'amazon',
                          ifelse(str_detect(employer_name,'cisco sys'),'cisco',
                          ifelse(str_detect(employer_name,'facebook'),'facebook',
                          ifelse(str_detect(employer_name,'google'),'google',
                          ifelse(str_detect(employer_name, 'ibm'),'ibm', employer_name))))))))
```

# define job level & data related & sde related 
```{r}
DATA <- DATA %>% 
  mutate(job_level=case_when(grepl("senior",job_title) ~ "high level",
                             grepl("director",job_title) ~ "high level",
                             grepl("lead",job_title) ~ "high level",
                             grepl("chief",job_title) ~ "high level",
                             grepl("principal",job_title) ~ "high level",
                             TRUE ~ "undefined")) %>% 
  mutate(data_relation=case_when(grepl("data",job_title) ~ "data_related",
                                 grepl("analy",job_title) ~ "data_related",
                                 grepl("machine learning",job_title) ~ "data_related",
                                 grepl("deep learning",job_title) ~ "data_related",
                                 grepl("intelligence",job_title) ~ "data_related",
                                 grepl("quantitative",job_title) ~ "data_related",
                                 grepl("statistic",job_title) ~ "data_related",
                                 grepl("sas",job_title) ~ "data_related",
                                 grepl("sql",job_title) ~ "data_related",
                                 grepl("oracle",job_title) ~ "data_related",
                                 grepl("spss",job_title) ~ "data_related",
                                 grepl("hadoop",job_title) ~ "data_related",
                                 TRUE ~ "undefined")) %>% 
  mutate(data_relation=case_when(grepl("program",job_title) ~ "undefined",
                                 grepl("system",job_title) ~ "undefined",
                                 grepl("tech",job_title) ~ "undefined",
                                 grepl("comput",job_title) ~ "undefined",
                                 TRUE ~ data_relation)) %>% 
  mutate(data_relation=case_when(grepl("business system analyst",job_title) ~ "data_related",
                                 TRUE ~ data_relation)) %>% 
  mutate(sde_relation=case_when(grepl("software",job_title) ~ "sde_related",
                                grepl("program",job_title) ~ "sde_related",
                                grepl("comput",job_title) ~ "sde_related",
                                grepl("system",job_title) ~ "sde_related",
                                grepl("tech",job_title) ~ "sde_related",
                                grepl("develop",job_title) ~ "sde_related",
                                TRUE ~ "undefined")) 
```

```{r}
DATA <- DATA %>% 
  mutate(data_job_title = 
           ifelse(str_detect(job_title,"business")&(str_detect(job_title,"analyst")|str_detect(job_title, "intelligence")), 
                  "Business Analyst", 
                  NA)) %>% 
  mutate(data_job_title = 
           ifelse(str_detect(job_title, "data")&(str_detect(job_title,"engineer")|str_detect(job_title, "warehouse")),
                  "Data Engineer", 
                  data_job_title)) %>% 
  mutate(data_job_title = 
           ifelse(str_detect(job_title, "data")&str_detect(job_title, "scientist"), 
                  "Data Scientist", 
                  data_job_title)) %>% 
  mutate(data_job_title = 
           ifelse(str_detect(job_title, "data")&str_detect(job_title, "analyst|analytics"), 
                  "Data Analyst", 
                  data_job_title)) %>% 
  mutate(data_job_title = 
           ifelse(str_detect(job_title, "machine|deep")&str_detect(job_title, "learning"), 
                  "Data Scientist", 
                  data_job_title)) %>% 
  mutate(data_job_title = 
           ifelse(str_detect(job_title, "product")&str_detect(job_title, "analyst|engineer|data"), 
                  "Data Analyst", 
                  data_job_title)) %>% 
  mutate(data_job_title = 
           ifelse(str_detect(job_title, "product")&str_detect(job_title, "manager"), 
                  "Product Manager", 
                  data_job_title)) 
  
```


# left_join: all stem occupations

```{r}
DATA <- DATA %>% 
  left_join(stem, by = "soc_code")
DATA <- DATA %>% 
  mutate(stem = ifelse(is.na(stem), 0, 1))
```


# filter certified status

```{r}
DATA <- DATA %>% 
  filter(case_status == "certified")

```



# make df for data job with the highest number in each city 

```{r}
filtered_job <- DATA %>% 
  filter(year == 2018) %>% 
  filter(data_job_title %in% c("Business Analyst","Data Analyst", "Data Engineer", "Data Scientist"))

df_18 <- filtered_job %>% 
  group_by(lon, lat, data_job_title) %>% 
  summarise(n = n()) %>% 
  pivot_wider(names_from = data_job_title, values_from = n) %>% 
  clean_names() 

df_18[is.na(df_18)] <- 0
df_18$max <- apply(df_18[c(3,4,5,6)], 1, max)
df_18
```

```{r}
# row_handler funtion - deal with each row
row_handler <- function(row.data){  
  index <- which(row.data == max(row.data))  # find the index of the max value
  out <- names(row.data[index])[1]  # get the column from index
  return(out)
}

# use row_handler function for each row, save the result to each row
df_18_max_nolat <- df_18[c(3,4,5,6)] %>%
  by_row(..f = row_handler, .collate = "rows", .to = "max_job")

df_18$max_job <- df_18_max_nolat$max_job
df_18 <- df_18 %>% 
  mutate(max_job = case_when(max_job == "business_analyst" ~ "Business Analyst",
                             max_job == "data_analyst" ~ "Data Analyst",
                             max_job == "data_engineer" ~ "Data Engineer",
                             max_job == "data_scientist" ~ "Data Scientist"))
points <- df_18 %>% 
  ungroup() %>% 
  select(lon, lat, max_job) %>% 
  slice(3:1499)

points
```

# import the US map
```{r}
data_dir <- "data/"
options(tigris_use_cache = TRUE, tigris_refresh = FALSE)

state_map_file  <- file.path(data_dir, "maps", "state_maps.Rds")
county_map_file <- file.path(data_dir, "maps", "county_maps.Rds")

if (file.exists(state_map_file)) {
  state_maps <- read_rds(state_map_file)
} else {
  state_maps <- states(cb = TRUE, year = 2016, progress_bar = FALSE, 
                       class = "sf") %>%
    clean_names() %>% rename(state = stusps)
  write_rds(state_maps, state_map_file)
}

if (file.exists(county_map_file)) {
  county_maps <- read_rds(county_map_file)
} else {
  county_maps <- counties(state = c(state.abb, "DC"), cb = TRUE, year = 2016, 
                          progress_bar = FALSE, class = "sf") %>%
    clean_names()
  write_rds(county_maps, county_map_file)
}

state_maps <- state_maps %>% 
  filter(state %in% c("AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY")) %>% 
  filter(! state %in% c("AK", "HI")) #%>%
  #st_transform("+init=epsg:5070")   # NAD83
```
