---
title: "20-job-level"
output: html_notebook
---
```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
h1b_df <- DATA

soc_tech_14 <- h1b_df %>% 
  filter(year == 2014) %>% 
  filter(soc_field == 15) %>% 
  group_by(employer_name) %>% 
  summarise(n = n()) %>% 
  arrange(-n) %>% 
  ungroup

soc_tech_18 <- h1b_df %>% 
  filter(year == 2018) %>% 
  filter(soc_field == 15) %>% 
  group_by(employer_name) %>% 
  summarise(n = n()) %>% 
  arrange(-n) %>% 
  ungroup

soc_10_14 <- soc_tech_14 %>% 
  top_n(15)

soc_10_18 <- soc_tech_18 %>% 
  top_n(15)

soc_top <- as.vector(intersect(soc_10_14$employer_name,soc_10_18$employer_name))
soc_top
```


# overall
## high level analysis
```{r}
highlevel_by_year <- DATA %>% 
  group_by(year, job_level) %>% 
  summarise(level_num = n()) 

highlevel_by_year
```

```{r}
ggplot(highlevel_by_year)+
  geom_line(aes(x=year,y=level_num,color=job_level), size = 1.05)+
  theme_bw()+
  labs(x="Year", y="Number of job level")
```

```{r}
highlevel_by_year %>% 
  group_by(year) %>% 
  mutate(sum=sum(level_num)) %>% 
  mutate(level_ratio=level_num / sum) %>%
  ungroup() %>% 
  filter(job_level == "high level") %>% 
  ggplot()+
  geom_line(aes(x=year,y=level_ratio), size = 1.05)+
  theme_bw()+
  labs(y="High level job ratio", x="Year")
```

## data related analysis

```{r}
data_related <- DATA %>% 
  select(year, data_relation,job_title ) %>% 
  arrange(-year) %>% 
  group_by(year, data_relation) %>% 
  summarise(type_sum = n()) 

data_related
```


```{r}
ggplot(data_related)+
  geom_line(aes(x=year,y=type_sum,color=data_relation), size = 1.05)+
  theme_bw()+
  labs(x="Year", y="Number of job type")
```

```{r}
data_related %>% 
  group_by(year) %>% 
  mutate(sum=sum(type_sum)) %>% 
  mutate(type_ratio=type_sum / sum) %>%
  ungroup() %>% 
  filter(data_relation == "data_related") %>% 
  ggplot()+
  geom_line(aes(x=year,y=type_ratio), size = 1.05)+
  theme_bw()+
  labs(y="Data related job ratio", x="Year")
```

# top analysis
## high level in top
```{r}
highlevel_in_top <- DATA %>% 
  filter(employer_name %in% soc_top) %>% 
  group_by(year, job_level) %>% 
  summarise(level_num = n()) 

highlevel_in_top
```

```{r}
ggplot(highlevel_in_top)+
  geom_line(aes(x=year,y=level_num,color=job_level), size = 1.05)+
  theme_bw()+
  labs(x="Year", y="Number of job level in top")
```

```{r}
DATA %>% 
  filter(employer_name %in% soc_top) %>% 
  group_by(year,employer_name, job_level) %>% 
  summarise(level_num = n()) %>% 
  group_by(year) %>% 
  mutate(sum=sum(level_num)) %>% 
  mutate(level_ratio=level_num / sum) %>%
  ungroup() %>% 
  filter(job_level == "high level") %>% 
  ggplot()+
  geom_line(aes(x=year,y=level_ratio,color=employer_name), size = 1.05)+
  theme_bw()+
  labs(y="High level job ratio in top", x="Year")


```

## data related in top
```{r}
data_related_in_top <- DATA %>% 
  filter(employer_name %in% soc_top) %>% 
  group_by(year, data_relation) %>% 
  summarise(type_sum = n()) 

data_related_in_top
```

```{r}
ggplot(data_related_in_top)+
  geom_line(aes(x=year,y=type_sum,color=data_relation), size = 1.05)+
  theme_bw()+
  labs(x="Year", y="Number of job type")
```

```{r}
DATA %>% 
  filter(employer_name %in% soc_top) %>% 
  group_by(year,employer_name, data_relation) %>% 
  summarise(type_sum = n())  %>% 
  group_by(year) %>% 
  mutate(sum=sum(type_sum)) %>% 
  mutate(type_ratio=type_sum / sum) %>%
  ungroup() %>% 
  filter(data_relation == "data_related") %>% 
  ggplot()+
  geom_line(aes(x=year,y=type_ratio,color=employer_name), size = 1.05)+
  theme_bw()+
  labs(y="Data related job ratio", x="Year")
```

# top tech analysis

```{r}

# soc_top_tech <- DATA %>% 
#   mutate(employer_name = ifelse(str_detect(employer_name,'apple inc'), 'Apple',
#                           ifelse(str_detect(employer_name,'microsoft'), 'Microsoft',
#                           ifelse(str_detect(employer_name,'amazon'),'Amazon',
#                           ifelse(str_detect(employer_name,'cisco sys'),'Cisco',
#                           ifelse(str_detect(employer_name,'facebook'),'Facebook',
#                           ifelse(str_detect(employer_name,'google'),'Google',
#                           ifelse(str_detect(employer_name, 'ibm'),'IBM','no'))))))))

# soc_top_tech <- c("apple",
#                   "microsoft",
#                   "intel",
#                   "facebook",
#                   "google",
#                   "ibm",
#                   "cisco sys")
```

## high level in top tech
```{r}
# highlevel_in_top_tech <- DATA %>%
#   filter(employer_name %in% soc_top_tech) %>%
#   group_by(year, job_level) %>%
#   summarise(level_num = n())
# 
# highlevel_in_top_tech
```

```{r}
# ggplot(highlevel_in_top_tech)+
#   geom_line(aes(x=year,y=level_num,color=job_level), size = 1.05)+
#   theme_bw()+
#   labs(x="Year", y="Number of job level in top")
```

```{r}
# DATA %>%
#   filter(employer_name %in% soc_top_tech) %>%
#   group_by(year,employer_name, job_level) %>%
#   summarise(level_num = n()) %>%
#   group_by(year) %>%
#   mutate(sum=sum(level_num)) %>%
#   mutate(level_ratio=level_num / sum) %>%
#   ungroup() %>%
#   filter(job_level == "high level") %>%
#   ggplot()+
#   geom_line(aes(x=year,y=level_ratio,color=employer_name), size = 1.05)+
#   theme_bw()+
#   labs(y="High level job ratio in top", x="Year")
```

## data related in top tech
```{r}
# data_related_in_top_tech <- DATA %>%
#   filter(employer_name %in% soc_top_tech) %>%
#   select(year,job_title,data_relation) %>% 
#   group_by(year, data_relation) %>%
#   summarise(type_sum = n())
# 
# data_related_in_top_tech
```

```{r}
# ggplot(data_related_in_top_tech)+
#   geom_line(aes(x=year,y=type_sum,color=data_relation), size = 1.05)+
#   theme_bw()+
#   labs(x="Year", y="Number of job type")
```

```{r}
# DATA %>%
#   filter(employer_name %in% soc_top_tech) %>%
#   group_by(year,employer_name, data_relation) %>%
#   summarise(type_sum = n())  %>%
#   group_by(year) %>%
#   mutate(sum=sum(type_sum)) %>%
#   mutate(type_ratio=type_sum / sum) %>%
#   ungroup() %>%
#   filter(data_relation == "data_related") %>%
#   ggplot()+
#   geom_line(aes(x=year,y=type_ratio,color=employer_name), size = 1.05)+
#   theme_bw()+
#   labs(y="Data related job ratio", x="Year")
```






#SDE
```{r}
# sde_related <- DATA %>% 
#   group_by(year, sde_relation) %>% 
#   summarise(type_sum = n()) 
# 
# sde_related
# 
# ggplot(sde_related)+
#   geom_line(aes(x=year,y=type_sum,color=sde_relation), size = 1.05)+
#   theme_bw()+
#   labs(x="Year", y="Number of job type")
#   #+coord_cartesian(ylim = c(0,400000))
# 
# sde_related %>% 
#   group_by(year) %>% 
#   mutate(sum=sum(type_sum)) %>% 
#   mutate(type_ratio=type_sum / sum) %>%
#   ungroup() %>% 
#   filter(sde_relation == "sde_related") %>% 
#   ggplot()+
#   geom_line(aes(x=year,y=type_ratio), size = 1.05)+
#   theme_bw()+
#   labs(y="Sde related job ratio", x="Year")
#   #+coord_cartesian(ylim = c(0,0.5))
```




```{r}
# DATA %>% 
#   filter(year == 2017) 
```

```{r}
# DATA %>% 
#   # mutate(sde_relation=case_when(grepl("software",job_title) ~ "sde_related",
#   #                               grepl("program",job_title) ~ "sde_related",
#   #                               grepl("comput",job_title) ~ "sde_related",
#   #                               grepl("system",job_title) ~ "sde_related",
#   #                               grepl("tech",job_title) ~ "sde_related",
#   #                               grepl("develop",job_title) ~ "sde_related",
#   #                               TRUE ~ "undefined")) %>%
#   # filter(sde_relation == "undefined") %>% 
#   
#   # filter(soc_field == "15") %>% 
#   
#   # mutate(data_relation=case_when(grepl("data",job_title) ~ "data_related",
#   #                                grepl("analy",job_title) ~ "data_related",
#   #                                grepl("machine learning",job_title) ~ "data_related",
#   #                                grepl("deep learning",job_title) ~ "data_related",
#   #                                grepl("intelligence",job_title) ~ "data_related",
#   #                                grepl("quantitative",job_title) ~ "data_related",
#   #                                grepl("statistic",job_title) ~ "data_related",
#   #                                grepl("sas",job_title) ~ "data_related",
#   #                                grepl("sql",job_title) ~ "data_related",
#   #                                grepl("oracle",job_title) ~ "data_related",
#   #                                grepl("spss",job_title) ~ "data_related",
#   #                                TRUE ~ "undefined")) %>% 
#   # filter(data_relation == "undefined") %>%
# 
#   filter(year == 2018 | year == 2017) %>% 
#   group_by(job_title,year) %>% 
#   summarise(n=n()) %>% 
#   arrange(-n) %>% 
#   pivot_wider(names_from = "year",
#               values_from = "n"
#               ) %>% 
#   mutate(ratio_2017 = `2017` / 622688 ) %>% 
#   mutate(ratio_2018 = `2018` / 652968 ) %>% 
# 
#   mutate(increase_num = `2018` - `2017`) %>% 
#   mutate(increase_ratio = ratio_2018 - ratio_2017) %>% 
# 
#   arrange(-increase_ratio)
```




# test MA

```{r}
df_18_ma <- filtered_job %>% 
  filter(worksite_state_abb=="MA") %>% 
  group_by(lon, lat, data_job_title) %>% 
  summarise(n = n()) %>% 
  pivot_wider(names_from = data_job_title, values_from = n) %>% 
  clean_names() 

df_18_ma[is.na(df_18_ma)] <- 0
df_18_ma$max <- apply(df_18_ma[c(3,4,5,6)], 1, max)
df_18_ma



df_18_ma_max_nolat <- df_18_ma[c(3,4,5,6)] %>%
  by_row(..f = row_handler, .collate = "rows", .to = "max_job")

df_18_ma$max_job <- df_18_ma_max_nolat$max_job
df_18_ma <- df_18_ma %>% 
  mutate(max_job = case_when(max_job == "business_analyst" ~ "Business Analyst",
                             max_job == "data_analyst" ~ "Data Analyst",
                             max_job == "data_engineer" ~ "Data Engineer",
                             max_job == "data_scientist" ~ "Data Scientist"))
points_ma <- df_18_ma %>% 
  ungroup() %>% 
  select(lon, lat, max_job) %>% 
  slice(1:90)

points_ma


state_maps_ma <- state_maps %>% 
  filter(state == "MA")

```

```{r}
ggplot(points_ma) + 
  geom_sf(data = state_maps_ma, color = "white", fill = "lightgrey",alpha=0.5) +
  geom_point(aes(x = jitter(lon), y = jitter(lat), color = max_job), size = 1, alpha = 0.5) + 
  scale_color_manual(values = c("Business Analyst" = "#00B2E4", 
                                "Data Analyst" = "#0F2A48",
                                "Data Engineer" = "#008B8B",
                                "Data Scientist" = "#FC2967"),
                     name = "Job Title") +
  theme(panel.background = element_blank(),
        legend.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        #legend.position = c(0,0), legend.justification = c(0,0)
        )+
  labs(x = "", y = "", title = "")
```


```{r}
northeast_states<- c("ME","VT","NH","MA","NY","RI","CT","NJ","DE","DC","PA","MD","DC")
```

```{r}
northeast_states<- c("ME","VT","NH","MA","NY","RI","CT","NJ","DE","DC","PA","MD","DC")

df_18_northeast <- filtered_job %>% 
  filter(worksite_state_abb %in% northeast_states) %>% 
  group_by(lon, lat, data_job_title) %>% 
  summarise(n = n()) %>% 
  pivot_wider(names_from = data_job_title, values_from = n) %>% 
  clean_names() 

df_18_northeast[is.na(df_18_northeast)] <- 0
df_18_northeast$max <- apply(df_18_northeast[c(3,4,5,6)], 1, max)
df_18_northeast



df_18_northeast_max_nolat <- df_18_northeast[c(3,4,5,6)] %>%
  by_row(..f = row_handler, .collate = "rows", .to = "max_job")

df_18_northeast$max_job <- df_18_northeast_max_nolat$max_job
df_18_northeast <- df_18_northeast %>% 
  mutate(max_job = case_when(max_job == "business_analyst" ~ "Business Analyst",
                             max_job == "data_analyst" ~ "Data Analyst",
                             max_job == "data_engineer" ~ "Data Engineer",
                             max_job == "data_scientist" ~ "Data Scientist"))
points_northeast <- df_18_northeast %>% 
  ungroup() %>% 
  select(lon, lat, max_job)  %>% 
  slice(1:596)

points_northeast


state_maps_northeast <- state_maps %>% 
  filter(state %in% northeast_states)

```

```{r}
ggplot(points_northeast) + 
  geom_sf(data = state_maps_northeast, color = "white", fill = "lightgrey",alpha=0.5) +
  geom_point(aes(x = jitter(lon), y = jitter(lat), color = max_job), size = 1, alpha = 0.5) + 
  scale_color_manual(values = c("Business Analyst" = "#00B2E4", 
                                "Data Analyst" = "#0F2A48",
                                "Data Engineer" = "#008B8B",
                                "Data Scientist" = "#FC2967"),
                     name = "Job Title") +
  theme(panel.background = element_blank(),
        legend.background = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        #legend.position = c(0,0), legend.justification = c(0,0)
        )+
  labs(x = "", y = "", title = "")
```


