---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
library(tidyverse)
```
```{r}
require(devtools)
install_github('ramnathv/rCharts@dev')
install_github('ramnathv/rMaps')
library(rMaps)
```


```{r}
DATA_certificate <- DATA %>% 
  filter(case_status=="certified") %>% 
  group_by(worksite_state_abb,year) %>% 
  summarise(num=n())
```

```{r}
d1 <-
  ichoropleth(
    num ~ worksite_state_abb,
    data = DATA_certificate,
    animate = 'year',
    ncuts = 9,
    legend = FALSE,
    geographyConfig = list(
      popupTemplate = "#!function(geo, data) {return '<div class=\"hoverinfo\"><strong>' + data.worksite_state_abb + '<br>' + data.num + '</strong></div>';}!#"
    )
  )
```



```{r}
d1$save('rMaps.html', cdn = TRUE)
```

## Data Related Jobs for different states

```{r}
DATA_data_related <- DATA %>% 
  filter(case_status=="certified") %>% 
  filter(data_relation=="data_related") %>%
  select(worksite_state_abb,year) %>% 
  group_by(worksite_state_abb,year) %>% 
  summarise(num=n())
  
```

```{r}
d2 <-
  ichoropleth(
    num ~ worksite_state_abb,
    data = DATA_data_related,
    animate = 'year',
    ncuts = 9,
    legend = FALSE,
    geographyConfig = list(
      popupTemplate = "#!function(geo, data) {return '<div class=\"hoverinfo\"><strong>' + data.worksite_state_abb + '<br>' + data.num + '</strong></div>';}!#"
    )
  )
d2
```

```{r}
d2$save('rMaps2.html', cdn = TRUE)
```

