---
title: "Presentation"
output: html_notebook
---


```{r}
library(tidyverse)
library(ggplot2)
library(readr)
library(ggpubr)
library("gridExtra")
```

```{r}
p1 <- DATA %>% 
  mutate(case_recode = case_when(case_status == 'certified' ~ 'certified',
                                 TRUE ~ 'not certified')) %>% 
  group_by(year, case_recode) %>% 
  summarise(n = n()) %>% 
  pivot_wider(names_from = "case_recode",
               values_from = "n") %>% 
  mutate(pp = certified / (certified + `not certified`), 
         total = certified + `not certified`) %>% 
  ggplot(aes(x = year, y = pp)) +
  geom_point()+
  geom_line() +
 # coord_cartesian(ylim = c(0, 1)) + 
  scale_y_continuous(labels = function(x){paste0(x*100, '%')}) +
  theme_minimal() +
  labs(y="certified proportion", x="\n Year")

p1


p2 <- DATA %>% 
  mutate(case_recode = case_when(case_status == 'certified' ~ 'certified',
                                 TRUE ~ 'not certified')) %>% 
  group_by(year, case_recode) %>% 
  summarise(n = n()) %>% 

  ggplot(aes(x = year, y = n, fill = case_recode)) +
  
  geom_bar(stat = "identity", position = position_stack(reverse = TRUE), alpha = 0.8) +
  #coord_cartesian(ylim = c(0000, 850000)) + 
  # geom_col(alpha = 0.5) +
  labs(title="The number of applicants through out years: 2014 - 2018", y="Number \n", x="\n Year") + 
  scale_fill_discrete(name = "Case status") +
  scale_y_continuous(labels = function(x){paste0(x/1000, 'K')}) + 
  theme_minimal() + 
  theme(plot.title = element_text(hjust=0.5))
 
grid.arrange(p1, p2, nrow  = 1)
```


